version: "3"
services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/demo
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:9.6
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432"

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    ports:
      - "6379"

volumes:
  pg-data:
  redis-data:
