version: "3"
services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/demo
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432"

volumes:
  db-data:
